-- SCRIPT 01: CREACION DE USUARIO DE BASE DE DATOS


-- Crear usuario KITS
CREATE USER KITS IDENTIFIED BY Kits2025;

-- Asignacion de permisos para la conexion a Oracle
GRANT CONNECT TO KITS;
GRANT RESOURCE TO KITS;

-- Asignacion de permisos para objetos
GRANT ALTER ANY INDEX TO KITS;
GRANT ALTER ANY SEQUENCE TO KITS;
GRANT ALTER ANY TABLE TO KITS;
GRANT ALTER ANY TRIGGER TO KITS;
GRANT CREATE ANY INDEX TO KITS;
GRANT CREATE ANY SEQUENCE TO KITS;
GRANT CREATE ANY SYNONYM TO KITS;
GRANT CREATE ANY TABLE TO KITS;
GRANT CREATE ANY TRIGGER TO KITS;
GRANT CREATE ANY VIEW TO KITS;
GRANT CREATE ANY PROCEDURE TO KITS;
GRANT CREATE PROCEDURE TO KITS;
GRANT CREATE PUBLIC SYNONYM TO KITS;
GRANT CREATE TRIGGER TO KITS;
GRANT CREATE VIEW TO KITS;
GRANT DELETE ANY TABLE TO KITS;
GRANT DROP ANY INDEX TO KITS;
GRANT DROP ANY SEQUENCE TO KITS;
GRANT DROP ANY TABLE TO KITS;
GRANT DROP ANY TRIGGER TO KITS;
GRANT DROP ANY VIEW TO KITS;
GRANT INSERT ANY TABLE TO KITS;
GRANT QUERY REWRITE TO KITS;
GRANT SELECT ANY TABLE TO KITS;
GRANT UNLIMITED TABLESPACE TO KITS;